### ISSUE TITLE
Is this crate still maintained?

### ISSUE THREAD

**Issue by JordanLloydHall** [mtshiba/crate-inspector#1]
Hello, I see that this crate has not been updated in the past 10 months. 
Is this crate still maintained? Are you looking for any active contributors?

Many thanks,
Jordan

**Comment by mtshiba** [comment]
Yes, it is being maintained. I've just released v0.2.0 with the latest dependencies.

I believe that all basic features of this crate are already implemented. Please let me know if you have any issues or feature requests. Contributions are also welcome.

**Comment by JordanLloydHall** [comment]
Thank you so much, I completely missed the 0.2.0 tag when I was looking for recent contributions.
Have a great day!
